local CONFIG = {
	["Common"] = { -- Rarity
		["Orange Car"] = { -- Model Name
			Earnings = 15,
			BaseTime = 60,
			
			Icons = {
				Normal = "rbxassetid://100378056095272",
				Gold = "rbxassetid://100378056095272",
				Diamond = "rbxassetid://100378056095272",
				Emerald = "rbxassetid://100378056095272",
				Blood = "rbxassetid://100378056095272",
			},
		},
		["Red Car"] = {
			Earnings = 25,
			BaseTime = 60,
			
			Icons = {
				Normal = "rbxassetid://74457629885906",
				Gold = "rbxassetid://74457629885906",
				Diamond = "rbxassetid://74457629885906",
				Emerald = "rbxassetid://74457629885906",
				Blood = "rbxassetid://74457629885906",
			},
		},
	},
	["Uncommon"] = {
		["Green Car"] = {
			Earnings = 35,
			BaseTime = 50,
			
			Icons = {
				Normal = "rbxassetid://106352808274301",
				Gold = "rbxassetid://106352808274301",
				Diamond = "rbxassetid://106352808274301",
				Emerald = "rbxassetid://106352808274301",
				Blood = "rbxassetid://106352808274301",
			},
		},
		["Rolls Car"] = {
			Earnings = 45,
			BaseTime = 50,
			
			Icons = {
				Normal = "rbxassetid://119334840758630",
				Gold = "rbxassetid://119334840758630",
				Diamond = "rbxassetid://119334840758630",
				Emerald = "rbxassetid://119334840758630",
				Blood = "rbxassetid://119334840758630",
			},
		},
	},
	["Rare"] = {
		["Muscle Car"] = {
			Earnings = 50,
			BaseTime = 50,
			
			Icons = {
				Normal = "rbxassetid://99195633163762",
				Gold = "rbxassetid://99195633163762",
				Diamond = "rbxassetid://99195633163762",
				Emerald = "rbxassetid://99195633163762",
				Blood = "rbxassetid://99195633163762",
			},
		},
		["Orange Car"] = {
			Earnings = 65,
			BaseTime = 50,
			
			Icons = {
				Normal = "rbxassetid://100378056095272",
				Gold = "rbxassetid://100378056095272",
				Diamond = "rbxassetid://100378056095272",
				Emerald = "rbxassetid://100378056095272",
				Blood = "rbxassetid://100378056095272",
			},
		},
	},
	["Epic"] = {
		["Rolls Car"] = {
			Earnings = 75,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://119334840758630",
				Gold = "rbxassetid://119334840758630",
				Diamond = "rbxassetid://119334840758630",
				Emerald = "rbxassetid://119334840758630",
				Blood = "rbxassetid://119334840758630",
			},
		},
		["Muscle Car"] = {
			Earnings = 85,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://99195633163762",
				Gold = "rbxassetid://99195633163762",
				Diamond = "rbxassetid://99195633163762",
				Emerald = "rbxassetid://99195633163762",
				Blood = "rbxassetid://99195633163762",
			},
		},
	},
	["Legendary"] = {
		["Super Car"] = {
			Earnings = 85,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://82088017614579",
				Gold = "rbxassetid://82088017614579",
				Diamond = "rbxassetid://82088017614579",
				Emerald = "rbxassetid://82088017614579",
				Blood = "rbxassetid://82088017614579",
			},
		},
		["Rolls Car"] = {
			Earnings = 95,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://119334840758630",
				Gold = "rbxassetid://119334840758630",
				Diamond = "rbxassetid://119334840758630",
				Emerald = "rbxassetid://119334840758630",
				Blood = "rbxassetid://119334840758630",
			},
		},
	},
	["Mythical"] = {
		["Super Car"] = {
			Earnings = 85,
			BaseTime = 40,

			Icons = {
				Normal = "rbxassetid://82088017614579",
				Gold = "rbxassetid://82088017614579",
				Diamond = "rbxassetid://82088017614579",
				Emerald = "rbxassetid://82088017614579",
				Blood = "rbxassetid://82088017614579",
			},
		},
		["Rolls Car"] = {
			Earnings = 120,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://119334840758630",
				Gold = "rbxassetid://119334840758630",
				Diamond = "rbxassetid://119334840758630",
				Emerald = "rbxassetid://119334840758630",
				Blood = "rbxassetid://119334840758630",
			},
		},
	},
	["Cosmic"] = {
		["Super Car"] = {
			Earnings = 85,
			BaseTime = 40,

			Icons = {
				Normal = "rbxassetid://82088017614579",
				Gold = "rbxassetid://82088017614579",
				Diamond = "rbxassetid://82088017614579",
				Emerald = "rbxassetid://82088017614579",
				Blood = "rbxassetid://82088017614579",
			},
		},
		["Rolls Car"] = {
			Earnings = 175,
			BaseTime = 40,
			
			Icons = {
				Normal = "rbxassetid://119334840758630",
				Gold = "rbxassetid://119334840758630",
				Diamond = "rbxassetid://119334840758630",
				Emerald = "rbxassetid://119334840758630",
				Blood = "rbxassetid://119334840758630",
			},
		},
	},
	["Secret"] = {
		["Super Car"] = {
			Earnings = 85,
			BaseTime = 40,

			Icons = {
				Normal = "rbxassetid://82088017614579",
				Gold = "rbxassetid://82088017614579",
				Diamond = "rbxassetid://82088017614579",
				Emerald = "rbxassetid://82088017614579",
				Blood = "rbxassetid://82088017614579",
			},
		},
	},
	["Exclusive"] = {
		["Black Car"] = {
			Earnings = 5000,
			
			Icons = {
				Normal = "rbxassetid://89343425855887",
			},
		},
	},
}

return CONFIG